services:
  youtube_bot-core:
    build:
      context: .
      dockerfile: docker_build/Dockerfile
    restart: always
    volumes:
      - type: bind
        source: ./
        target: /tmp/
        read_only: false
